// Hand-curated list of companies and peer groups tracked by Dashboard 1.
// Edit this file to add or remove tickers; the ingestion script reads it.
//
// Step 11 universe: top-20 Indian IT-services companies from the Screener
// IT sector PDFs (page 1) plus a shortlist of page-2 names parked as
// future candidates with fetchEnabled = false.
//
// NSE symbols and BSE codes below are publicly listed identifiers from
// the exchanges. Reverify against the current exchange directory before
// any production deploy; tickers can change with corporate actions.

import type {
  CompanyMaster,
  PeerGroup,
} from "../../src/data/types/dhammaDashboard";

// Active universe — 20 companies, all fetchEnabled=true. The first four
// have been fetched in production; the remaining sixteen are armed but
// not yet verified end-to-end. Their `sourceNotes` flag the
// reverification requirement.
export const COMPANIES: CompanyMaster[] = [
  {
    companyId: "tcs",
    displayName: "TCS",
    legalName: "Tata Consultancy Services Limited",
    nseSymbol: "TCS",
    bseCode: "532540",
    exchanges: [
      { exchange: "NSE", symbol: "TCS" },
      { exchange: "BSE", symbol: "532540" },
    ],
    country: "IN",
    sector: "Information Technology",
    industry: "IT Services & Consulting",
    peerGroupId: "it-services-broad",
    fiscalYearEndMonth: 3,
    reportingBasisDefault: "consolidated",
    irPageUrl: "https://www.tcs.com/investor-relations",
    status: "active",
    screenerSlug: "TCS",
    screenerUrl: "https://www.screener.in/company/TCS/",
    fetchEnabled: true,
    fetchPriority: 1,
    sourceNotes:
      "Screener slug = NSE symbol TCS. Verified end-to-end (production data).",
    notes: "Top-4 IT services large-cap. Reverify identifiers periodically.",
  },
  {
    companyId: "infosys",
    displayName: "Infosys",
    legalName: "Infosys Limited",
    nseSymbol: "INFY",
    bseCode: "500209",
    exchanges: [
      { exchange: "NSE", symbol: "INFY" },
      { exchange: "BSE", symbol: "500209" },
    ],
    country: "IN",
    sector: "Information Technology",
    industry: "IT Services & Consulting",
    peerGroupId: "it-services-broad",
    fiscalYearEndMonth: 3,
    reportingBasisDefault: "consolidated",
    irPageUrl: "https://www.infosys.com/investors/",
    status: "active",
    screenerSlug: "INFY",
    screenerUrl: "https://www.screener.in/company/INFY/",
    fetchEnabled: true,
    fetchPriority: 2,
    sourceNotes:
      "Screener slug = NSE symbol INFY. Verified end-to-end (production data).",
    notes: "Top-4 IT services large-cap.",
  },
  {
    companyId: "hcltech",
    displayName: "HCLTech",
    legalName: "HCL Technologies Limited",
    nseSymbol: "HCLTECH",
    bseCode: "532281",
    exchanges: [
      { exchange: "NSE", symbol: "HCLTECH" },
      { exchange: "BSE", symbol: "532281" },
    ],
    country: "IN",
    sector: "Information Technology",
    industry: "IT Services & Consulting",
    peerGroupId: "it-services-broad",
    fiscalYearEndMonth: 3,
    reportingBasisDefault: "consolidated",
    irPageUrl: "https://www.hcltech.com/investors",
    status: "active",
    screenerSlug: "HCLTECH",
    screenerUrl: "https://www.screener.in/company/HCLTECH/",
    fetchEnabled: true,
    fetchPriority: 3,
    sourceNotes:
      "Screener slug = NSE symbol HCLTECH. Verified end-to-end (production data).",
    notes: "Top-4 IT services large-cap.",
  },
  {
    companyId: "wipro",
    displayName: "Wipro",
    legalName: "Wipro Limited",
    nseSymbol: "WIPRO",
    bseCode: "507685",
    exchanges: [
      { exchange: "NSE", symbol: "WIPRO" },
      { exchange: "BSE", symbol: "507685" },
    ],
    country: "IN",
    sector: "Information Technology",
    industry: "IT Services & Consulting",
    peerGroupId: "it-services-broad",
    fiscalYearEndMonth: 3,
    reportingBasisDefault: "consolidated",
    irPageUrl: "https://www.wipro.com/investors/",
    status: "active",
    screenerSlug: "WIPRO",
    screenerUrl: "https://www.screener.in/company/WIPRO/",
    fetchEnabled: true,
    fetchPriority: 4,
    sourceNotes:
      "Screener slug = NSE symbol WIPRO. Verified end-to-end (production data).",
    notes: "Top-4 IT services large-cap.",
  },
  // -------------------------------------------------------------------------
  // Step 11 additions — slugs inferred from NSE symbols. fetchEnabled=true
  // but each row's sourceNotes asks the next workflow run to verify that
  // the screenerSlug really resolves to a non-empty Screener page. If
  // it doesn't, the per-company status row in screener-fetch-status.json
  // will show the failure and we can flip fetchEnabled=false here.
  // -------------------------------------------------------------------------
  {
    companyId: "techm",
    displayName: "Tech Mahindra",
    legalName: "Tech Mahindra Limited",
    nseSymbol: "TECHM",
    bseCode: null,
    exchanges: [{ exchange: "NSE", symbol: "TECHM" }],
    country: "IN",
    sector: "Information Technology",
    industry: "IT Services & Consulting",
    peerGroupId: "it-services-broad",
    fiscalYearEndMonth: 3,
    reportingBasisDefault: "consolidated",
    irPageUrl: null,
    status: "active",
    screenerSlug: "TECHM",
    screenerUrl: "https://www.screener.in/company/TECHM/",
    fetchEnabled: true,
    fetchPriority: 5,
    sourceNotes:
      "Slug inferred from NSE symbol TECHM. Verify next workflow run lands rows; if not, flip fetchEnabled=false.",
    notes: "Top-5 IT services peer.",
  },
  {
    companyId: "ltim",
    displayName: "LTIMindtree",
    legalName: "LTIMindtree Limited",
    nseSymbol: "LTIM",
    bseCode: null,
    exchanges: [{ exchange: "NSE", symbol: "LTIM" }],
    country: "IN",
    sector: "Information Technology",
    industry: "IT Services & Consulting",
    peerGroupId: "it-services-broad",
    fiscalYearEndMonth: 3,
    reportingBasisDefault: "consolidated",
    irPageUrl: null,
    status: "active",
    screenerSlug: "LTIM",
    screenerUrl: "https://www.screener.in/company/LTIM/",
    fetchEnabled: true,
    fetchPriority: 6,
    sourceNotes:
      "Slug inferred from NSE symbol LTIM (post-merger ticker). Verify after first fetch.",
    notes: "Top-tier IT peer.",
  },
  {
    companyId: "ofss",
    displayName: "Oracle Financial Services",
    legalName: "Oracle Financial Services Software Limited",
    nseSymbol: "OFSS",
    bseCode: null,
    exchanges: [{ exchange: "NSE", symbol: "OFSS" }],
    country: "IN",
    sector: "Information Technology",
    industry: "IT Software Products",
    peerGroupId: "it-services-broad",
    fiscalYearEndMonth: 3,
    reportingBasisDefault: "consolidated",
    irPageUrl: null,
    status: "active",
    screenerSlug: "OFSS",
    screenerUrl: "https://www.screener.in/company/OFSS/",
    fetchEnabled: true,
    fetchPriority: 7,
    sourceNotes:
      "Slug inferred from NSE symbol OFSS. Verify after first fetch.",
    notes: "Software products; included in Screener IT peer set.",
  },
  {
    companyId: "persistent",
    displayName: "Persistent Systems",
    legalName: "Persistent Systems Limited",
    nseSymbol: "PERSISTENT",
    bseCode: null,
    exchanges: [{ exchange: "NSE", symbol: "PERSISTENT" }],
    country: "IN",
    sector: "Information Technology",
    industry: "IT Services & Consulting",
    peerGroupId: "it-services-broad",
    fiscalYearEndMonth: 3,
    reportingBasisDefault: "consolidated",
    irPageUrl: null,
    status: "active",
    screenerSlug: "PERSISTENT",
    screenerUrl: "https://www.screener.in/company/PERSISTENT/",
    fetchEnabled: true,
    fetchPriority: 8,
    sourceNotes:
      "Slug inferred from NSE symbol PERSISTENT. Verify after first fetch.",
    notes: "Mid-cap IT peer.",
  },
  {
    companyId: "coforge",
    displayName: "Coforge",
    legalName: "Coforge Limited",
    nseSymbol: "COFORGE",
    bseCode: null,
    exchanges: [{ exchange: "NSE", symbol: "COFORGE" }],
    country: "IN",
    sector: "Information Technology",
    industry: "IT Services & Consulting",
    peerGroupId: "it-services-broad",
    fiscalYearEndMonth: 3,
    reportingBasisDefault: "consolidated",
    irPageUrl: null,
    status: "active",
    screenerSlug: "COFORGE",
    screenerUrl: "https://www.screener.in/company/COFORGE/",
    fetchEnabled: true,
    fetchPriority: 9,
    sourceNotes:
      "Slug inferred from NSE symbol COFORGE. Verify after first fetch.",
    notes: "Mid-cap IT peer.",
  },
  {
    companyId: "mphasis",
    displayName: "Mphasis",
    legalName: "Mphasis Limited",
    nseSymbol: "MPHASIS",
    bseCode: null,
    exchanges: [{ exchange: "NSE", symbol: "MPHASIS" }],
    country: "IN",
    sector: "Information Technology",
    industry: "IT Services & Consulting",
    peerGroupId: "it-services-broad",
    fiscalYearEndMonth: 3,
    reportingBasisDefault: "consolidated",
    irPageUrl: null,
    status: "active",
    screenerSlug: "MPHASIS",
    screenerUrl: "https://www.screener.in/company/MPHASIS/",
    fetchEnabled: true,
    fetchPriority: 10,
    sourceNotes:
      "Slug inferred from NSE symbol MPHASIS. Verify after first fetch.",
    notes: "Mid-cap IT peer.",
  },
  {
    companyId: "ltts",
    displayName: "L&T Technology Services",
    legalName: "L&T Technology Services Limited",
    nseSymbol: "LTTS",
    bseCode: null,
    exchanges: [{ exchange: "NSE", symbol: "LTTS" }],
    country: "IN",
    sector: "Information Technology",
    industry: "IT Services & Consulting (ER&D)",
    peerGroupId: "it-services-broad",
    fiscalYearEndMonth: 3,
    reportingBasisDefault: "consolidated",
    irPageUrl: null,
    status: "active",
    screenerSlug: "LTTS",
    screenerUrl: "https://www.screener.in/company/LTTS/",
    fetchEnabled: true,
    fetchPriority: 11,
    sourceNotes:
      "Slug inferred from NSE symbol LTTS. Verify after first fetch.",
    notes: "Engineering R&D services peer.",
  },
  {
    companyId: "hexaware",
    displayName: "Hexaware Technologies",
    legalName: "Hexaware Technologies Limited",
    nseSymbol: "HEXT",
    bseCode: null,
    exchanges: [{ exchange: "NSE", symbol: "HEXT" }],
    country: "IN",
    sector: "Information Technology",
    industry: "IT Services & Consulting",
    peerGroupId: "it-services-broad",
    fiscalYearEndMonth: 12,
    reportingBasisDefault: "consolidated",
    irPageUrl: null,
    status: "active",
    screenerSlug: "HEXT",
    screenerUrl: "https://www.screener.in/company/HEXT/",
    fetchEnabled: true,
    fetchPriority: 12,
    sourceNotes:
      "Re-IPO'd in 2025. NSE symbol HEXT inferred; verify next workflow run. Note: calendar-year fiscal (Dec-end), unlike other peers.",
    notes:
      "Re-listed after PE buyout. Different FY-end means YoY math vs Mar-end peers may need adjustment.",
  },
  {
    companyId: "tatatech",
    displayName: "Tata Technologies",
    legalName: "Tata Technologies Limited",
    nseSymbol: "TATATECH",
    bseCode: null,
    exchanges: [{ exchange: "NSE", symbol: "TATATECH" }],
    country: "IN",
    sector: "Information Technology",
    industry: "IT Services & Consulting (ER&D)",
    peerGroupId: "it-services-broad",
    fiscalYearEndMonth: 3,
    reportingBasisDefault: "consolidated",
    irPageUrl: null,
    status: "active",
    screenerSlug: "TATATECH",
    screenerUrl: "https://www.screener.in/company/TATATECH/",
    fetchEnabled: true,
    fetchPriority: 13,
    sourceNotes:
      "Slug inferred from NSE symbol TATATECH (post-IPO 2023). Verify after first fetch.",
    notes: "ER&D services peer.",
  },
  {
    companyId: "tataelxsi",
    displayName: "Tata Elxsi",
    legalName: "Tata Elxsi Limited",
    nseSymbol: "TATAELXSI",
    bseCode: null,
    exchanges: [{ exchange: "NSE", symbol: "TATAELXSI" }],
    country: "IN",
    sector: "Information Technology",
    industry: "IT Services & Consulting (Design)",
    peerGroupId: "it-services-broad",
    fiscalYearEndMonth: 3,
    reportingBasisDefault: "consolidated",
    irPageUrl: null,
    status: "active",
    screenerSlug: "TATAELXSI",
    screenerUrl: "https://www.screener.in/company/TATAELXSI/",
    fetchEnabled: true,
    fetchPriority: 14,
    sourceNotes:
      "Slug inferred from NSE symbol TATAELXSI. Verify after first fetch.",
    notes: "Design + embedded services peer.",
  },
  {
    companyId: "kpittech",
    displayName: "KPIT Technologies",
    legalName: "KPIT Technologies Limited",
    nseSymbol: "KPITTECH",
    bseCode: null,
    exchanges: [{ exchange: "NSE", symbol: "KPITTECH" }],
    country: "IN",
    sector: "Information Technology",
    industry: "IT Services & Consulting (Automotive)",
    peerGroupId: "it-services-broad",
    fiscalYearEndMonth: 3,
    reportingBasisDefault: "consolidated",
    irPageUrl: null,
    status: "active",
    screenerSlug: "KPITTECH",
    screenerUrl: "https://www.screener.in/company/KPITTECH/",
    fetchEnabled: true,
    fetchPriority: 15,
    sourceNotes:
      "Slug inferred from NSE symbol KPITTECH. Verify after first fetch.",
    notes: "Automotive-software-focused peer.",
  },
  {
    companyId: "zensartech",
    displayName: "Zensar Technologies",
    legalName: "Zensar Technologies Limited",
    nseSymbol: "ZENSARTECH",
    bseCode: null,
    exchanges: [{ exchange: "NSE", symbol: "ZENSARTECH" }],
    country: "IN",
    sector: "Information Technology",
    industry: "IT Services & Consulting",
    peerGroupId: "it-services-broad",
    fiscalYearEndMonth: 3,
    reportingBasisDefault: "consolidated",
    irPageUrl: null,
    status: "active",
    screenerSlug: "ZENSARTECH",
    screenerUrl: "https://www.screener.in/company/ZENSARTECH/",
    fetchEnabled: true,
    fetchPriority: 16,
    sourceNotes:
      "Slug inferred from NSE symbol ZENSARTECH. Verify after first fetch.",
    notes: "Mid-cap IT peer.",
  },
  {
    companyId: "intellect",
    displayName: "Intellect Design",
    legalName: "Intellect Design Arena Limited",
    nseSymbol: "INTELLECT",
    bseCode: null,
    exchanges: [{ exchange: "NSE", symbol: "INTELLECT" }],
    country: "IN",
    sector: "Information Technology",
    industry: "IT Software Products",
    peerGroupId: "it-services-broad",
    fiscalYearEndMonth: 3,
    reportingBasisDefault: "consolidated",
    irPageUrl: null,
    status: "active",
    screenerSlug: "INTELLECT",
    screenerUrl: "https://www.screener.in/company/INTELLECT/",
    fetchEnabled: true,
    fetchPriority: 17,
    sourceNotes:
      "Slug inferred from NSE symbol INTELLECT. Verify after first fetch.",
    notes: "Banking software products peer.",
  },
  {
    companyId: "cyient",
    displayName: "Cyient",
    legalName: "Cyient Limited",
    nseSymbol: "CYIENT",
    bseCode: null,
    exchanges: [{ exchange: "NSE", symbol: "CYIENT" }],
    country: "IN",
    sector: "Information Technology",
    industry: "IT Services & Consulting (ER&D)",
    peerGroupId: "it-services-broad",
    fiscalYearEndMonth: 3,
    reportingBasisDefault: "consolidated",
    irPageUrl: null,
    status: "active",
    screenerSlug: "CYIENT",
    screenerUrl: "https://www.screener.in/company/CYIENT/",
    fetchEnabled: true,
    fetchPriority: 18,
    sourceNotes:
      "Slug inferred from NSE symbol CYIENT. Verify after first fetch.",
    notes: "ER&D services peer.",
  },
  {
    companyId: "birlasoft",
    displayName: "Birlasoft",
    legalName: "Birlasoft Limited",
    nseSymbol: "BSOFT",
    bseCode: null,
    exchanges: [{ exchange: "NSE", symbol: "BSOFT" }],
    country: "IN",
    sector: "Information Technology",
    industry: "IT Services & Consulting",
    peerGroupId: "it-services-broad",
    fiscalYearEndMonth: 3,
    reportingBasisDefault: "consolidated",
    irPageUrl: null,
    status: "active",
    screenerSlug: "BSOFT",
    screenerUrl: "https://www.screener.in/company/BSOFT/",
    fetchEnabled: true,
    fetchPriority: 19,
    sourceNotes:
      "Slug inferred from NSE symbol BSOFT (Birlasoft trades as BSOFT post-2019 rename from KPIT-Cummins demerger). Verify next workflow run.",
    notes: "Mid-cap IT peer.",
  },
  {
    companyId: "sonata",
    displayName: "Sonata Software",
    legalName: "Sonata Software Limited",
    nseSymbol: "SONATSOFTW",
    bseCode: null,
    exchanges: [{ exchange: "NSE", symbol: "SONATSOFTW" }],
    country: "IN",
    sector: "Information Technology",
    industry: "IT Services & Consulting",
    peerGroupId: "it-services-broad",
    fiscalYearEndMonth: 3,
    reportingBasisDefault: "consolidated",
    irPageUrl: null,
    status: "active",
    screenerSlug: "SONATSOFTW",
    screenerUrl: "https://www.screener.in/company/SONATSOFTW/",
    fetchEnabled: true,
    fetchPriority: 20,
    sourceNotes:
      "Slug inferred from NSE symbol SONATSOFTW. Verify after first fetch.",
    notes: "Mid-cap IT peer.",
  },
];

export const PEER_GROUPS: PeerGroup[] = [
  {
    peerGroupId: "it-services-broad",
    label: "Indian IT services — broad benchmark group",
    description:
      "20 publicly listed Indian IT-services companies sourced from Screener's IT sector PDFs (page 1). Used as the default peer set for KPI benchmark cards.",
    companyIds: [
      "tcs",
      "infosys",
      "hcltech",
      "wipro",
      "techm",
      "ltim",
      "ofss",
      "persistent",
      "coforge",
      "mphasis",
      "ltts",
      "hexaware",
      "tatatech",
      "tataelxsi",
      "kpittech",
      "zensartech",
      "intellect",
      "cyient",
      "birlasoft",
      "sonata",
    ],
    notes:
      "First 4 are verified end-to-end (production data). Other 16 are armed but pending verification on the next workflow run.",
  },
];

// -----------------------------------------------------------------------------
// Inactive future-candidate list — sourced from page 2 of Screener's IT
// sector PDFs (smaller-cap companies). NOT included in COMPANIES, NOT
// fetched, NOT in company-master.json. To activate one of these:
//   1. Move the entry into COMPANIES with fetchEnabled: true.
//   2. Add it to PEER_GROUPS[0].companyIds.
//   3. Run `npm run ingest:dhamma` then `npm run ingest:screener:fetch
//      --company <id>` to confirm the slug resolves.
// All slugs below are best-guess from the displayName; reverify before
// flipping fetchEnabled.
// -----------------------------------------------------------------------------
export interface InactiveCandidate {
  companyId: string;
  displayName: string;
  nseSymbolGuess: string | null;
  screenerSlugGuess: string | null;
  notes: string;
}

export const INACTIVE_IT_CANDIDATES: InactiveCandidate[] = [
  {
    companyId: "npst",
    displayName: "Network People Services Technologies",
    nseSymbolGuess: "NPST",
    screenerSlugGuess: "NPST",
    notes: "Fintech IT services. Recent SME → mainboard mover.",
  },
  {
    companyId: "protean",
    displayName: "Protean eGov Technologies",
    nseSymbolGuess: "PROTEAN",
    screenerSlugGuess: "PROTEAN",
    notes: "GovTech / e-services peer.",
  },
  {
    companyId: "ceinsys",
    displayName: "Ceinsys Tech",
    nseSymbolGuess: "CEINSYS",
    screenerSlugGuess: "CEINSYS",
    notes: "GIS / geospatial IT services.",
  },
  {
    companyId: "nucleus",
    displayName: "Nucleus Software",
    nseSymbolGuess: "NUCLEUS",
    screenerSlugGuess: "NUCLEUS",
    notes: "Banking products peer.",
  },
  {
    companyId: "saksoft",
    displayName: "Saksoft",
    nseSymbolGuess: "SAKSOFT",
    screenerSlugGuess: "SAKSOFT",
    notes: "Mid-/small-cap IT services peer.",
  },
  {
    companyId: "dlink",
    displayName: "D-Link India",
    nseSymbolGuess: "DLINKINDIA",
    screenerSlugGuess: "DLINKINDIA",
    notes: "Networking hardware; on edge of IT-services peer set.",
  },
  {
    companyId: "accelya",
    displayName: "Accelya Solutions",
    nseSymbolGuess: "ACCELYA",
    screenerSlugGuess: "ACCELYA",
    notes: "Airline-vertical IT services peer.",
  },
  {
    companyId: "infobeans",
    displayName: "InfoBeans Technologies",
    nseSymbolGuess: "INFOBEAN",
    screenerSlugGuess: "INFOBEAN",
    notes: "Small-cap IT services peer.",
  },
  {
    companyId: "ramcosys",
    displayName: "Ramco Systems",
    nseSymbolGuess: "RAMCOSYS",
    screenerSlugGuess: "RAMCOSYS",
    notes: "ERP products peer.",
  },
  {
    companyId: "expleo",
    displayName: "Expleo Solutions",
    nseSymbolGuess: "EXPLEOSOL",
    screenerSlugGuess: "EXPLEOSOL",
    notes: "Engineering + IT services peer.",
  },
  {
    companyId: "quickheal",
    displayName: "Quick Heal Technologies",
    nseSymbolGuess: "QUICKHEAL",
    screenerSlugGuess: "QUICKHEAL",
    notes: "Cybersecurity products peer.",
  },
  {
    companyId: "nintec",
    displayName: "NINtec Systems",
    nseSymbolGuess: null,
    screenerSlugGuess: null,
    notes:
      "Ticker uncertain. Verify exact name and listing status against NSE/BSE before adding.",
  },
  {
    companyId: "ksolves",
    displayName: "Ksolves India",
    nseSymbolGuess: "KSOLVES",
    screenerSlugGuess: "KSOLVES",
    notes: "Small-cap IT services peer.",
  },
  {
    companyId: "subex",
    displayName: "Subex",
    nseSymbolGuess: "SUBEXLTD",
    screenerSlugGuess: "SUBEXLTD",
    notes: "Telecom-IT services peer.",
  },
  {
    companyId: "onward",
    displayName: "Onward Technologies",
    nseSymbolGuess: "ONWARDTEC",
    screenerSlugGuess: "ONWARDTEC",
    notes: "ER&D services peer.",
  },
];
